version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - mynetwork
    volumes:
      - ./app/data:./app/data
    restart: on-failure
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - mynetwork
    restart: on-failure

networks:
 mynetwork: